# Generated by Django 4.0.2 on 2024-02-27 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_news_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
