# Generated by Django 4.0.2 on 2024-02-27 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Widget',
        ),
    ]
